
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.aurorasmpnew.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.item.Item;

import net.mcreator.aurorasmpnew.item.ZiulItem;
import net.mcreator.aurorasmpnew.item.YunoBloodmoonItem;
import net.mcreator.aurorasmpnew.item.WillianMutuwaItem;
import net.mcreator.aurorasmpnew.item.WarrionItem;
import net.mcreator.aurorasmpnew.item.TyphonItem;
import net.mcreator.aurorasmpnew.item.TyperItem;
import net.mcreator.aurorasmpnew.item.TridenteModularItem;
import net.mcreator.aurorasmpnew.item.TiaraItem;
import net.mcreator.aurorasmpnew.item.SuiccinivItem;
import net.mcreator.aurorasmpnew.item.SculpItem;
import net.mcreator.aurorasmpnew.item.RumberItem;
import net.mcreator.aurorasmpnew.item.RukyItem;
import net.mcreator.aurorasmpnew.item.RevenItem;
import net.mcreator.aurorasmpnew.item.RayItem;
import net.mcreator.aurorasmpnew.item.PeitoralModularItem;
import net.mcreator.aurorasmpnew.item.NumItem;
import net.mcreator.aurorasmpnew.item.ManoplaItem;
import net.mcreator.aurorasmpnew.item.LeviathanScaleItem;
import net.mcreator.aurorasmpnew.item.LeviathanItem;
import net.mcreator.aurorasmpnew.item.LeobargueItem;
import net.mcreator.aurorasmpnew.item.KammuItem;
import net.mcreator.aurorasmpnew.item.KairosItem;
import net.mcreator.aurorasmpnew.item.JasonKatanaItem;
import net.mcreator.aurorasmpnew.item.IsotitaItem;
import net.mcreator.aurorasmpnew.item.IsakielItem;
import net.mcreator.aurorasmpnew.item.HottoItem;
import net.mcreator.aurorasmpnew.item.HollowItem;
import net.mcreator.aurorasmpnew.item.FoiceTheClownItem;
import net.mcreator.aurorasmpnew.item.FlechaMagicaItem;
import net.mcreator.aurorasmpnew.item.EspadaModularItem;
import net.mcreator.aurorasmpnew.item.DustItem;
import net.mcreator.aurorasmpnew.item.CrucifixoItem;
import net.mcreator.aurorasmpnew.item.CristalVermelhoItem;
import net.mcreator.aurorasmpnew.item.CristalVerdeItem;
import net.mcreator.aurorasmpnew.item.CristalRoxoItem;
import net.mcreator.aurorasmpnew.item.CristalPretoItem;
import net.mcreator.aurorasmpnew.item.CristalLaranjaItem;
import net.mcreator.aurorasmpnew.item.CristalCianoItem;
import net.mcreator.aurorasmpnew.item.CristalBrancoItem;
import net.mcreator.aurorasmpnew.item.CristalAzulItem;
import net.mcreator.aurorasmpnew.item.CristalAmareloItem;
import net.mcreator.aurorasmpnew.item.CigarroItem;
import net.mcreator.aurorasmpnew.item.BehemothSpearItem;
import net.mcreator.aurorasmpnew.item.AuroraencyclopediaItem;
import net.mcreator.aurorasmpnew.item.AuroraDimensionItem;
import net.mcreator.aurorasmpnew.item.ArcoModularItem;
import net.mcreator.aurorasmpnew.item.AlineItem;
import net.mcreator.aurorasmpnew.item.ATYPowerItem;
import net.mcreator.aurorasmpnew.item.ATYItem;
import net.mcreator.aurorasmpnew.item.AMOEBAItem;
import net.mcreator.aurorasmpnew.AurorasmpnewMod;

public class AurorasmpnewModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, AurorasmpnewMod.MODID);
	public static final RegistryObject<Item> JASON_KATANA = REGISTRY.register("jason_katana", () -> new JasonKatanaItem());
	public static final RegistryObject<Item> MANOPLA = REGISTRY.register("manopla", () -> new ManoplaItem());
	public static final RegistryObject<Item> FOICE_THE_CLOWN = REGISTRY.register("foice_the_clown", () -> new FoiceTheClownItem());
	public static final RegistryObject<Item> BEHEMOTH_SPEAR = REGISTRY.register("behemoth_spear", () -> new BehemothSpearItem());
	public static final RegistryObject<Item> TRIDENTE_MODULAR = REGISTRY.register("tridente_modular", () -> new TridenteModularItem());
	public static final RegistryObject<Item> ESPADA_MODULAR = REGISTRY.register("espada_modular", () -> new EspadaModularItem());
	public static final RegistryObject<Item> PEITORAL_MODULAR = REGISTRY.register("peitoral_modular", () -> new PeitoralModularItem());
	public static final RegistryObject<Item> ARCO_MODULAR = REGISTRY.register("arco_modular", () -> new ArcoModularItem());
	public static final RegistryObject<Item> LEVIATHAN_HELMET = REGISTRY.register("leviathan_helmet", () -> new LeviathanItem.Helmet());
	public static final RegistryObject<Item> LEVIATHAN_CHESTPLATE = REGISTRY.register("leviathan_chestplate", () -> new LeviathanItem.Chestplate());
	public static final RegistryObject<Item> LEVIATHAN_LEGGINGS = REGISTRY.register("leviathan_leggings", () -> new LeviathanItem.Leggings());
	public static final RegistryObject<Item> LEVIATHAN_BOOTS = REGISTRY.register("leviathan_boots", () -> new LeviathanItem.Boots());
	public static final RegistryObject<Item> LEVIATHAN_SCALE = REGISTRY.register("leviathan_scale", () -> new LeviathanScaleItem());
	public static final RegistryObject<Item> FLECHA_MAGICA = REGISTRY.register("flecha_magica", () -> new FlechaMagicaItem());
	public static final RegistryObject<Item> CIGARRO = REGISTRY.register("cigarro", () -> new CigarroItem());
	public static final RegistryObject<Item> AMOEBA = REGISTRY.register("amoeba", () -> new AMOEBAItem());
	public static final RegistryObject<Item> AURORAENCYCLOPEDIA = REGISTRY.register("auroraencyclopedia", () -> new AuroraencyclopediaItem());
	public static final RegistryObject<Item> TIARA = REGISTRY.register("tiara", () -> new TiaraItem());
	public static final RegistryObject<Item> CRISTAL_AMARELO = REGISTRY.register("cristal_amarelo", () -> new CristalAmareloItem());
	public static final RegistryObject<Item> CRISTAL_AZUL = REGISTRY.register("cristal_azul", () -> new CristalAzulItem());
	public static final RegistryObject<Item> CRISTAL_BRANCO = REGISTRY.register("cristal_branco", () -> new CristalBrancoItem());
	public static final RegistryObject<Item> CRISTAL_CIANO = REGISTRY.register("cristal_ciano", () -> new CristalCianoItem());
	public static final RegistryObject<Item> CRISTAL_LARANJA = REGISTRY.register("cristal_laranja", () -> new CristalLaranjaItem());
	public static final RegistryObject<Item> CRISTAL_ROXO = REGISTRY.register("cristal_roxo", () -> new CristalRoxoItem());
	public static final RegistryObject<Item> CRISTAL_VERDE = REGISTRY.register("cristal_verde", () -> new CristalVerdeItem());
	public static final RegistryObject<Item> CRISTAL_VERMELHO = REGISTRY.register("cristal_vermelho", () -> new CristalVermelhoItem());
	public static final RegistryObject<Item> CRISTAL_PRETO = REGISTRY.register("cristal_preto", () -> new CristalPretoItem());
	public static final RegistryObject<Item> AURORA_DIMENSION = REGISTRY.register("aurora_dimension", () -> new AuroraDimensionItem());
	public static final RegistryObject<Item> HOLLOW = REGISTRY.register("hollow", () -> new HollowItem());
	public static final RegistryObject<Item> ISOTITA = REGISTRY.register("isotita", () -> new IsotitaItem());
	public static final RegistryObject<Item> TYPER = REGISTRY.register("typer", () -> new TyperItem());
	public static final RegistryObject<Item> WARRION = REGISTRY.register("warrion", () -> new WarrionItem());
	public static final RegistryObject<Item> KAIROS = REGISTRY.register("kairos", () -> new KairosItem());
	public static final RegistryObject<Item> RUKY = REGISTRY.register("ruky", () -> new RukyItem());
	public static final RegistryObject<Item> WILLIAN_MUTUWA = REGISTRY.register("willian_mutuwa", () -> new WillianMutuwaItem());
	public static final RegistryObject<Item> SCULP = REGISTRY.register("sculp", () -> new SculpItem());
	public static final RegistryObject<Item> ZIUL = REGISTRY.register("ziul", () -> new ZiulItem());
	public static final RegistryObject<Item> YUNO_BLOODMOON = REGISTRY.register("yuno_bloodmoon", () -> new YunoBloodmoonItem());
	public static final RegistryObject<Item> LEOBARGUE = REGISTRY.register("leobargue", () -> new LeobargueItem());
	public static final RegistryObject<Item> ISAKIEL = REGISTRY.register("isakiel", () -> new IsakielItem());
	public static final RegistryObject<Item> SUICCINIV = REGISTRY.register("suicciniv", () -> new SuiccinivItem());
	public static final RegistryObject<Item> REVEN = REGISTRY.register("reven", () -> new RevenItem());
	public static final RegistryObject<Item> RUMBER = REGISTRY.register("rumber", () -> new RumberItem());
	public static final RegistryObject<Item> ALINE = REGISTRY.register("aline", () -> new AlineItem());
	public static final RegistryObject<Item> RAY = REGISTRY.register("ray", () -> new RayItem());
	public static final RegistryObject<Item> DUST = REGISTRY.register("dust", () -> new DustItem());
	public static final RegistryObject<Item> HOTTO = REGISTRY.register("hotto", () -> new HottoItem());
	public static final RegistryObject<Item> KAMMU = REGISTRY.register("kammu", () -> new KammuItem());
	public static final RegistryObject<Item> TYPHON = REGISTRY.register("typhon", () -> new TyphonItem());
	public static final RegistryObject<Item> ATY = REGISTRY.register("aty", () -> new ATYItem());
	public static final RegistryObject<Item> ATY_POWER = REGISTRY.register("aty_power", () -> new ATYPowerItem());
	public static final RegistryObject<Item> NUM = REGISTRY.register("num", () -> new NumItem());
	public static final RegistryObject<Item> CRUCIFIXO = REGISTRY.register("crucifixo", () -> new CrucifixoItem());
}
